# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: check-poetry
-   repo: https://github.com/google/yapf
    rev: v0.40.0
    hooks:
    -   id: yapf
